### ISSUE TITLE
Error Can create only one Bot Second it can't

### ISSUE THREAD

**Issue by FrankyOwen** [sefirosweb/minecraftLegion#17]
Bot broken: ad
Error: Error: Command failed: node C:\Users\ASUS\Desktop\Bot\minecraftLegion\core\dist\start_bot.js ad
Mineflayer detected that you are using a deprecated event (physicTick)! Please use this event (physicsTick) instead.
node:events:490
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::4550
    at Server.setupListenHandle [as _listen2] (node:net:1774:16)
    at listenInCluster (node:net:1822:12)
    at Server.listen (node:net:1910:7)
    at StateMachineWebserver.startServer (C:\Users\ASUS\Desktop\Bot\minecraftLegion\core\node_modules\mineflayer-statemachine\lib\webserver.js:52:14)
    at startStateMachine (C:\Users\ASUS\Desktop\Bot\minecraftLegion\core\dist\NestedStateModules\MainStateMachine.js:172:17)
    at EventEmitter.<anonymous> (C:\Users\ASUS\Desktop\Bot\minecraftLegion\core\dist\createNewBot.js:93:37)
    at Object.onceWrapper (node:events:626:28)
    at EventEmitter.emit (node:events:524:35)
    at Client.<anonymous> (C:\Users\ASUS\Desktop\Bot\minecraftLegion\core\node_modules\mineflayer\lib\plugins\health.js:13:11)
    at Object.onceWrapper (node:events:627:26)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1801:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 4550
}

Node.js v19.8.1

**Comment by sefirosweb** [comment]
Disable DEBUG_MODE to false
```
DEBUG_MODE=false
```

This error happens when debug is active an both bots is trying to use same port for state machine (debug mode)
