### ISSUE TITLE
Don't understand

### ISSUE THREAD

**Issue by Wylabb** [sefirosweb/minecraftLegion#6]
(base) makarnovozilov@MacBook-Air-Makar minecraftLegion-0.1.6 % node start_bot.js Huilo
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'mineflayer'
Require stack:
- /Users/makarnovozilov/Downloads/minecraftLegion-0.1.6/start_bot.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/makarnovozilov/Downloads/minecraftLegion-0.1.6/start_bot.js:2:20)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/makarnovozilov/Downloads/minecraftLegion-0.1.6/start_bot.js'
  ]
}

**Comment by sefirosweb** [comment]
Hi this error means you not installed dependecies

Execute first ```npm install```
