### ISSUE TITLE
Bots disconnect shortly after joining

### ISSUE THREAD

**Issue by TheCrazyInsanity** [sefirosweb/minecraftLegion#8]
it outputs this in console

Error: write ECONNABORTED
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at Socket._writeGeneric (net.js:785:11)
    at Socket._write (net.js:797:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Socket.Writable.write (internal/streams/writable.js:303:10)
    at Cipheriv.ondata (internal/streams/readable.js:719:22)
    at Cipheriv.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9) {
  errno: -4079,
  code: 'ECONNABORTED',
  syscall: 'write'
}

idk im stupid

**Comment by sefirosweb** [comment]
Hi sorry, this bot is not 100% fine have a bit bugs,

In localhost vanilla minecraft version must be work fine,

**Comment by ItzFaruq** [comment]
I think that's just your internet being unstable, because I also experienced something like that

**Comment by sefirosweb** [comment]
You still have the issue? for a now i close the ticket,

Also i'm adding method for use in docker, for avoid problems about node versions,
