### ISSUE TITLE
I can't start this bot following the tutorial.

### ISSUE THREAD

**Issue by BOTVergil** [sefirosweb/minecraftLegion#9]
I can't start this bot following the tutorial.
And minecraftLegionWebServer & minecraftLegionWebClient cannot be downloaded.

**Comment by sefirosweb** [comment]
minecraftLegionWebServer & minecraftLegionWebClient is also open source in git,

you cant clone the repositories?
https://github.com/sefirosweb/minecraftLegionWebServer
https://github.com/sefirosweb/minecraftLegionWebClient

Wich error you have?

I know I need to improve or make a video tutorial

**Comment by BOTVergil** [comment]
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@modules/botWebsocket'
Require stack:
- D:\botjuntuan\node_modules\minecraftlegion\start_bot.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._resolveFilename (D:\botjuntuan\node_modules\module-alias\index.js:49:29)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\botjuntuan\node_modules\minecraftlegion\start_bot.js:3:22)        
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'D:\\botjuntuan\\node_modules\\minecraftlegion\\start_bot.js' ]
}

**Comment by sefirosweb** [comment]
Hi Bot, sorry for delay,

It is a bit strange,  could you check dhe packae.json file?

For load @module I used alias for load from root,

![image](https://user-images.githubusercontent.com/20754836/150692027-363d3d6d-eddb-4334-9e66-4ff124080b1c.png)

Exist this line in your package.json?

**Comment by BOTVergil** [comment]
Exist this line in my package.json

**Comment by sefirosweb** [comment]
Hi @BOTVergil  I upload a recently video to how to install the bot,

You can check that https://www.youtube.com/watch?v=E6arfQxYKlw&t=17s
